### ISSUE TITLE
More indicative HD5 exceptions

### ISSUE THREAD

**Issue by robstewart57** [mokus0/hs-hdf5#1]
Hi,

I'd like to know whether the show instance for `HD5Error` is printing what you would expect.  For a failed call attempt to `createFile`, I see the following error:

```
*** Exception: HDF5Exception [HDF5Error {classId = hdfError, majorNum = Just Args, minorNum = Just (UnknownMinor (HId_t 0x0c000019)), line = 1412, funcName = "0^\ETX\164\204\DEL", fileName = "P^\ETX\164\204\DEL", description = "p^\ETX\164\204\DEL"}
```

To remind you, in `Bindings.HD5.Error` , these values are read from CString's in `readHD5Error` as:

```
readHDF5Error :: H5E_error2_t -> IO HDF5Error
readHDF5Error err = do
    func <- BS.packCString (h5e_error2_t'func_name err)
    file <- BS.packCString (h5e_error2_t'file_name err)
    desc <- BS.packCString (h5e_error2_t'desc err)

    return HDF5Error
        { classId       = ErrorClassID (h5e_error2_t'cls_id err)
        , majorNum      = majorErrorFromCode (h5e_error2_t'maj_num err)
        , minorNum      = minorErrorFromCode (h5e_error2_t'maj_num err)
        , line          = toInteger (h5e_error2_t'line err)
        , funcName      = func
        , fileName      = file
        , description   = desc
        }
```

For example, the print of the function name is `funcName = "0^\ETX\164\204\DEL"` . Is the Exception thrown what you'd expect?

**Comment by mokus0** [comment]
No, I'd definitely expect more informative messages.  Would you mind giving a little more background, such as OS, architecture, GHC and HDF5 versions?

Thanks!

**Comment by robstewart57** [comment]
Sure, no problem.

```
$ uname -a
Linux rob-desktop 3.5.0-24-generic #37-Ubuntu SMP Thu Feb 7 01:50:30 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.4.2
$ sudo aptitude show libhdf5-dev
Package: libhdf5-dev                     
State: installed
Version: 1.8.8-9
```

**Comment by mokus0** [comment]
Thanks.  I have a VM with close to the same configuration, I'll take a look when I get some time this weekend and see if I can figure out what's going on here.

**Comment by mokus0** [comment]
Interesting, I don't know whether something changed in HDF5 or I just didn't notice this bug earlier, but the problem is that the code that calls `readHDF5Error` collects up all the pointers to the error frames and then reads them all at once.  I thought that the strings were kept around as long as the stack, but if that was once true it is no longer.

In any case, the code now reads the frames as it traverses the stack, and appears to be working correctly now.
